from turtle import *
from random import *

setup(width = 800, height = 500)
speed(8)
penup()
goto(-300,200)
right(90)
pendown()
forward(400)
penup()
backward(400)
left(90)
write(0)

for i in range(1, 11) :
    forward(60)
    right(90)
    pendown()
    forward(400)
    penup()
    backward(400)
    left(90)
    write(i)
hideturtle()

a = Turtle()
a.shape('turtle')
a.color('red')
a.shapesize(2)
a.penup()
a.goto(-300, 150)
a.right(360)
a.pendown()

b = Turtle()
b.shape('turtle')
b.color('blue')
b.shapesize(2)
b.penup()
b.goto(-300, 50)
b.left(360)
b.pendown()

c = Turtle()
c.shape('turtle')
c.color('green')
c.shapesize(2)
c.penup()
c.goto(-300, -50)
c.right(360)
c.pendown()

d = Turtle()
d.shape('turtle')
d.color('yellow')
d.shapesize(2)
d.penup()
d.goto(-300, -150)
d.left(360)
d.pendown()

for j in range(130) :
    a.forward(randint(1, 8))
    b.forward(randint(1, 8))
    c.forward(randint(1, 8))
    d.forward(randint(1, 8))